# Generated by Django 4.0.6 on 2024-02-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=99)),
                ('phone_number', models.CharField(max_length=99)),
                ('comment', models.TextField(blank=True, max_length=399)),
            ],
        ),
    ]
