# Generated by Django 4.0.6 on 2024-02-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='comment',
            field=models.TextField(blank=True, max_length=399, null=True),
        ),
    ]
